# 日志级别
error-level: "warn"

# 绑定端口服务
host: "localhost:8889"

# 跨域允许的源
allow-origin: ["http://localhost:5173"]

# 静态资源路径
static-dir: "../deploy/web"

# 前端站点根路径
web-root: "/web"

# 数据库配置
mysql:
  # 配置主库
  master: "username:password@tcp(ip:port)/database?parseTime=True&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci"
  sources: [
  ]
  # 配置从库
  replicas: [
  ]
  # 空闲连接池中连接的最大数量
  max-idle-conns: 10
  # 打开数据库连接的最大数量
  max-open-conns: 100
  # 连接可复用的最大时间
  conn-max-lifetime: 1h
  # 设置哪些表可被查询
  allow-table: []